ThibFr33/task_it

.gitignore
Gemfile
Gemfile.lock
config/initializers/openai.rb
config/routes.rb

Add openai

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_list_card_show.scss
app/controllers/lists_controller.rb
app/views/lists/show.html.erb
config/routes.rb

Création des actions new et show de ListsController et view de show

création lists#show

---

app/controllers/lists_controller.rb
app/controllers/tasks_controller.rb
app/javascript/controllers/submit_task_controller.js
app/views/lists/index.html.erb
app/views/lists/show.html.erb
config/routes.rb
db/migrate/20241127134205_add_done_to_tasks.rb
db/schema.rb

Création de l'index de Lists(back) et update de show d'une liste (back et début front)

creation index de list et update de list show

---

app/assets/stylesheets/components/_modal.scss
app/controllers/lists_controller.rb
app/views/dashboards/_modal.html.erb

front de la modal ok 
ajout d'un if dans l'index du dashboards

modal done

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_my_lists_title.scss
app/views/lists/index.html.erb

Front de list-index ok

---

app/views/dashboards/_list_card.html.erb
app/views/dashboards/index.html.erb

comme dit dans le titre : liens cartes/id fait sur la homepage

liens avec id sur les cartes fait

---

app/assets/stylesheets/components/_cards.scss
app/views/lists/index.html.erb

Création link d'une liste vers la show de cette liste

 link lists index to show ok

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_list_card_show.scss
app/controllers/lists_controller.rb
app/helpers/application_helper.rb
app/views/dashboards/_list_card.html.erb
app/views/dashboards/index.html.erb

ajout du helper dans la partial list_card
stylisation du background image dans la partial SCSS cards
correction du end oublié dans controller lists

Add image category

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_list_card_show.scss
app/assets/stylesheets/components/_my_lists_title.scss
app/assets/stylesheets/components/_titles.scss
app/controllers/lists_controller.rb
app/views/lists/show.html.erb

J'ai update le front de la show d'une liste

update front List show

---

app/views/dashboards/index.html.erb
app/views/lists/show.html.erb

Add boolean value input for heroku
Merge validé avec Romain

Fix checkbox

---

app/controllers/lists_controller.rb
app/controllers/tasks_controller.rb
app/javascript/controllers/submit_task_controller.js
app/models/list.rb
app/views/lists/show.html.erb
config/routes.rb

Ajout d'une tache OK , tri par ordre ascendant quand checked

create a task done

---

app/views/lists/show.html.erb

label fixed

---

app/services/ocr_lists.rb

heroku ocr fixed

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_list_card_show.scss
app/assets/stylesheets/components/_loader.scss
app/controllers/lists_controller.rb
app/jobs/ocr_list_job.rb
app/models/list.rb
app/services/ocr_list.rb
app/views/lists/_loader.html.erb
app/views/lists/show.html.erb
bin/jobs
config/application.rb
config/cable.yml
config/environments/production.rb
config/puma.rb
config/queue.yml
config/recurring.yml
db/migrate/20241202140446_create_solid_cable_message.solid_cable.rb
db/migrate/20241202140447_index_channels.solid_cable.rb
db/migrate/20241202141814_install_solid_queue.rb
db/schema.rb
test/jobs/ocr_list_job_test.rb

change input by icon
loader partial html et css 
mise en place de Job pour plus tard

Change input ocr

---

app/controllers/reminders_controller.rb
app/javascript/controllers/flatpickr_controller.js
app/javascript/controllers/timepicker_controller.js

flatpickr et reminders page fixed

flatpickr fixed

---

app/assets/stylesheets/components/_list_card_show.scss
app/javascript/controllers/edit_controller.js
app/views/lists/show.html.erb
config/puma.rb

Mise en place edit de List.
Check de l'edit.
Retouche de front à finir.

Front edit lists

---

app/assets/stylesheets/components/_list_card_show.scss
app/views/lists/show.html.erb
app/views/tasks/_task.html.erb

Edit de tasks in progress  !!!

 edit tasks in progress, Turbo

---

app/assets/stylesheets/components/_list_card_show.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_reminder_button.scss
app/views/reminders/edit.html.erb
app/views/reminders/index.html.erb
app/views/reminders/show.html.erb
app/views/shared/_navbar.html.erb

Destroy reminders

---

app/controllers/reminders_controller.rb
app/services/ocr_reminder.rb
app/views/reminders/new.html.erb

problèmes sur ocr index résouts
suppression de l'ocr dans le create aucun intérêt a prendre juste la description et remplir le reste à la main alors que tout est dans le scan

problems solves

---

app/assets/stylesheets/components/_button.scss
app/views/dashboards/_modal.html.erb
app/views/devise/sessions/new.html.erb
app/views/reminders/index.html.erb
config/locales/devise.en.yml
db/seeds.rb

Fix click buttons (connexion page + list creation)
Change devise native labels

fix click buttons + labels

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_list_card_show.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_reminder_card.scss
app/views/dashboards/_reminder_card.html.erb
app/views/dashboards/index.html.erb
app/views/lists/show.html.erb
app/views/reminders/edit.html.erb
app/views/reminders/index.html.erb
app/views/shared/_navbar.html.erb
app/views/tasks/_task.html.erb

ajustements front et calendrier des rappels dans l'index

mid demo front

---

app/views/lists/index.html.erb

Nom de domaine ajouté sur Heroku
Action Destroy ajouté à l'index des listes.

 destroy_list OK

---

app/assets/stylesheets/components/_loader.scss
app/controllers/lists_controller.rb
app/javascript/controllers/submit_photo_controller.js
app/jobs/ocr_list_job.rb
app/services/ocr_list.rb
app/views/lists/_list_tasks.html.erb
app/views/lists/show.html.erb
app/views/reminders/index.html.erb
app/views/shared/_loader.html.erb
app/views/tasks/_task.html.erb
config/puma.rb

loader sur list
suppression du ok/valider pour ocr list et reminder

Loader finish

---

app/assets/stylesheets/components/_reminder_card.scss
app/views/reminders/index.html.erb

fix emplacement de la poubelle par rapport à la div reminders

changement trash emplacement

---

app/assets/stylesheets/components/_list_card_show.scss
app/views/lists/show.html.erb
app/views/tasks/_task.html.erb
config/initializers/simple_form_bootstrap.rb

Reprise du front du détail d'une liste

lists formatting

---

app/assets/stylesheets/components/_list_card_show.scss
app/views/lists/show.html.erb

Color fixed

---

app/controllers/tasks_controller.rb

 task-update OK

---

app/controllers/reminders_controller.rb

Changement redirect de reminder

reminder path fixed
